/*
 *     Generated by class-dump 3.1.1.
 *
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 *
 *  BlueTap was released to the public domain, 2010-02-28
 */

#import <UIKit/UIKit.h>

@class BluetoothAudioJack, NSMutableArray;

@interface BluetoothManager : NSObject
{
        struct BTHandsfreeServiceImpl *_handsfreeService;
        struct BTLocalDeviceImpl *_localDevice;
        struct BTSessionImpl *_session;
        BOOL _audioConnected;
        BOOL _scanningEnabled;
        BOOL _pairingEnabled;
        int _powerState;
        struct BTDiscoveryAgentImpl *_discoveryAgent;
        struct BTPairingAgentImpl *_pairingAgent;
        struct BTAccessoryManagerImpl *_accessoryManager;
        NSMutableArray *_devices;
        BluetoothAudioJack *_audioJack;
}

+ (id)sharedInstance;
+ (void)initialize;
- (void)cleanup;
- (void)dealloc;
- (void)_postNotificationWithArray:(id)fp8;
- (void)_postNotification:(id)fp8;
- (void)postNotification:(id)fp8;
- (void)postNotificationName:(id)fp8 object:(id)fp12;
- (void)_setupSession;
- (void)_setupLocalDevice;
- (void)_setupHandsfreeService;
- (void)_setupAccessoryManager;
- (void)_setup;
- (void)serverTerminated;
- (id)init;
- (BOOL)connected;
- (BOOL)powered;
- (void)_powerChanged:(BOOL)fp8;
- (BOOL)setPowered:(BOOL)fp8;
- (void)setAirplaneMode:(BOOL)fp8;
- (BOOL)enabled;
- (BOOL)setEnabled:(BOOL)fp8;
- (BOOL)audioConnected;
- (void)setAudioConnected:(BOOL)fp8;
- (id)_existingWrapperForDevice:(struct BTDeviceImpl *)fp8;
- (id)addDeviceIfNeeded:(struct BTDeviceImpl *)fp8;
- (void)setDeviceScanningEnabled:(BOOL)fp8;
- (BOOL)deviceScanningEnabled;
- (void)setDevicePairingEnabled:(BOOL)fp8;
- (BOOL)devicePairingEnabled;
- (void)setPincode:(id)fp8 forDevice:(id)fp12;
- (void)connectDevice:(id)fp8;
- (void)pairDevice:(id)fp8;
- (void)cancelPairing;
- (BOOL)canBeConnected;
- (id)connectableDevices;
- (id)pairedDevices;
- (void)unpairDevice:(id)fp8;
- (BOOL)isDiscoverable;
- (void)setDiscoverable:(BOOL)fp8;
- (BOOL)connectable;
- (void)setConnectable:(BOOL)fp8;
- (id)audioJack;
- (void)enableTestMode;

@end
